# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-22 10:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('industry_type', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_number', models.IntegerField()),
                ('company_type', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='cmpny_logo')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('Keywords', models.TextField()),
                ('work_experienc_min', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)], max_length=100)),
                ('work_experienc_mix', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)], max_length=100)),
                ('annual_ctc', models.CharField(max_length=100)),
                ('number_of_vacancies', models.IntegerField()),
                ('location', models.IntegerField()),
                ('industry', models.CharField(choices=[('IT-Software / Software Services', 'IT-Software / Software Services'), ('BPO / Call Centre / ITES', 'BPO / Call Centre / ITES'), ('Automobile / Auto Anciliary / Auto Components', 'Automobile / Auto Anciliary / Auto Components'), ('Accounting / Finance', 'Accounting / Finance'), ('Advertising / PR / MR / Event Management', 'Advertising / PR / MR / Event Management'), ('Agriculture / Dairy', 'Agriculture / Dairy'), ('Animation / Gaming', 'Animation / Gaming'), ('Architecture / Interior Design', 'Architecture / Interior Design'), ('Aviation / Aerospace Firms', 'Aviation / Aerospace Firms'), ('Banking / Financial Services / Broking', 'Banking / Financial Services / Broking'), ('Brewery / Distillery', 'Brewery / Distillery'), ('Broadcasting', 'Broadcasting'), ('Consumer Electronics / Appliances / Durables', 'Consumer Electronics / Appliances / Durables'), ('Education / Teaching / Training', 'Education / Teaching / Training'), ('Electricals / Switchgears', 'Electricals / Switchgears')], max_length=100)),
                ('functional_area', models.CharField(choices=[('IT-Software / Software Services', 'IT-Software / Software Services'), ('BPO / Call Centre / ITES', 'BPO / Call Centre / ITES'), ('Automobile / Auto Anciliary / Auto Components', 'Automobile / Auto Anciliary / Auto Components'), ('Accounting / Finance', 'Accounting / Finance'), ('Advertising / PR / MR / Event Management', 'Advertising / PR / MR / Event Management'), ('Agriculture / Dairy', 'Agriculture / Dairy'), ('Animation / Gaming', 'Animation / Gaming'), ('Architecture / Interior Design', 'Architecture / Interior Design'), ('Aviation / Aerospace Firms', 'Aviation / Aerospace Firms'), ('Banking / Financial Services / Broking', 'Banking / Financial Services / Broking'), ('Brewery / Distillery', 'Brewery / Distillery'), ('Broadcasting', 'Broadcasting'), ('Consumer Electronics / Appliances / Durables', 'Consumer Electronics / Appliances / Durables'), ('Education / Teaching / Training', 'Education / Teaching / Training'), ('Electricals / Switchgears', 'Electricals / Switchgears')], max_length=100)),
                ('job_role', models.CharField(max_length=100)),
                ('qualifications', models.CharField(choices=[('Graduation', 'Graduation'), ('Post Graduation', 'Post Graduation'), ('Ph.D', 'Ph.D')], max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
