# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-22 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingdetails',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userRegistration.CompanyProfile'),
        ),
    ]
