# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-08 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0003_auto_20170307_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openingdetails',
            old_name='annual_ctc',
            new_name='annual_ctc_max',
        ),
        migrations.RenameField(
            model_name='openingdetails',
            old_name='work_experienc_mix',
            new_name='work_experienc_max',
        ),
        migrations.AddField(
            model_name='openingdetails',
            name='annual_ctc_min',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
