# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-08 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0005_auto_20170308_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openingdetails',
            name='Keywords',
        ),
        migrations.AddField(
            model_name='openingdetails',
            name='contact_email',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openingdetails',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='openingdetails',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
