# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-09 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0007_auto_20170308_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingdetails',
            name='job_id',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
