# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-09 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0008_openingdetails_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
